server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/pmp_server?serverTimezone=UTC
    username: root
    password: 19980518
  redis:
    host: localhost
    port: 6379
    timeout: 3000

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml