server:
  port: 8080

spring:
  profiles:
    active: application-pc-dev
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/pmp_server?serverTimezone=UTC
  redis:
    host: localhost
    port: 6379
    timeout: 3000
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
